### ISSUE TITLE
drilldown issue: TypeError: g.doDrilldown is not a function

### ISSUE THREAD

**Issue by jeffshaver** [kirjs/react-highcharts#115]
Ever since updating to 8.0.2 from 7.x, I get this error when doing drilldowns: `TypeError: g.doDrilldown is not a function`

This is the code in the module that imports everything:

```
import React, {Component, PropTypes} from 'react'
import Highcharts from 'highcharts'
import ReactHighcharts from 'react-highcharts'
import HighchartsData from 'highcharts-data'
import HighchartsDrilldown from 'highcharts-drilldown'

HighchartsData(ReactHighcharts.Highcharts)
HighchartsDrilldown(ReactHighcharts.Highcharts)
```

**Comment by kirjs** [comment]
Try doing the same without react-highcharts, and let me know if that works

**Comment by jeffshaver** [comment]
@kirjs it seems like it only happens when two different modules use drilldown.

So like say i have a 2 components. One that makes a column chart and one that makes a pie chart. if both of them run the code above, it gives the error. If only one loads the drilldown stuff it runs fine. Am I supposed to be doing the import of Highcharts and the HighchartsData/HighchartsDrilldown at a higher level so that it only happens once?

**Comment by kirjs** [comment]
That could be the reason. 
There probably should be a way to register drilldown for a particular Highcharts instance

**Comment by kirjs** [comment]
```jsx
var HighchartsMore = require('highcharts-more');
HighchartsMore(ReactHighcharts.Highcharts);
```
This is how more does it, see if you can do the same for the drilldown

**Comment by jeffshaver** [comment]
@kirjs doing it that was, it still gives the error when there is more than one chart that wants drilldowns. So I went into the App component, loaded the drilldown and data modules and ran them once and it seems to work.

Can you think of the reason this would happen? It seems like I would want to be able to choose per module?

**Comment by jeffshaver** [comment]
Also confusing because it seems like you don't need to import highcarts even though the readme/examples says you have to

**Comment by kirjs** [comment]
Requiring highcharts directly is not needed anymore, I revomed it from the readme, please let me know where it is in examples so that I could remove it as well.

**Comment by jeffshaver** [comment]
@kirjs maybe its just me, but this is confusing: https://github.com/kirjs/react-highcharts/blob/master/demo/src/more.jsx#L2

Saying `Note that Highcharts has to be required separately` means to me that I need to include it or import it or something. I believe this comment appears in almost all of the examples/demos.

**Comment by kirjs** [comment]
Thanks, I changed the wording

**Comment by Strateus** [comment]
This helped me:
HighchartsDrilldown(ReactHighcharts**.Highcharts**);

**Comment by Theraghav** [comment]
I am using highcharts and meteor. There are two different charts on different pages where using highcharts drilldown module. Had to remove importing drill-down from the second module and the error was gone. 

So I had to import highcharts in both the places but import drilldown module only once.
